/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EletrocalhaRouteImport } from './routes/eletrocalha'
import { Route as EletrodutoRouteImport } from './routes/eletroduto'
import { Route as EnvelopeRouteImport } from './routes/envelope'
import { Route as MemoriaRouteImport } from './routes/memoria'
import { Route as NormaRouteImport } from './routes/norma'
import { Route as QuadroRouteImport } from './routes/quadro'
import { Route as TabelasRouteImport } from './routes/tabelas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EletrocalhaRoute = EletrocalhaRouteImport.update({
  id: '/eletrocalha',
  path: '/eletrocalha',
  getParentRoute: () => rootRouteImport,
} as any)
const EletrodutoRoute = EletrodutoRouteImport.update({
  id: '/eletroduto',
  path: '/eletroduto',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvelopeRoute = EnvelopeRouteImport.update({
  id: '/envelope',
  path: '/envelope',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriaRoute = MemoriaRouteImport.update({
  id: '/memoria',
  path: '/memoria',
  getParentRoute: () => rootRouteImport,
} as any)
const NormaRoute = NormaRouteImport.update({
  id: '/norma',
  path: '/norma',
  getParentRoute: () => rootRouteImport,
} as any)
const QuadroRoute = QuadroRouteImport.update({
  id: '/quadro',
  path: '/quadro',
  getParentRoute: () => rootRouteImport,
} as any)
const TabelasRoute = TabelasRouteImport.update({
  id: '/tabelas',
  path: '/tabelas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/eletrocalha': typeof EletrocalhaRoute
  '/eletroduto': typeof EletrodutoRoute
  '/envelope': typeof EnvelopeRoute
  '/memoria': typeof MemoriaRoute
  '/norma': typeof NormaRoute
  '/quadro': typeof QuadroRoute
  '/tabelas': typeof TabelasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/eletrocalha': typeof EletrocalhaRoute
  '/eletroduto': typeof EletrodutoRoute
  '/envelope': typeof EnvelopeRoute
  '/memoria': typeof MemoriaRoute
  '/norma': typeof NormaRoute
  '/quadro': typeof QuadroRoute
  '/tabelas': typeof TabelasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/eletrocalha': typeof EletrocalhaRoute
  '/eletroduto': typeof EletrodutoRoute
  '/envelope': typeof EnvelopeRoute
  '/memoria': typeof MemoriaRoute
  '/norma': typeof NormaRoute
  '/quadro': typeof QuadroRoute
  '/tabelas': typeof TabelasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/eletrocalha'
    | '/eletroduto'
    | '/envelope'
    | '/memoria'
    | '/norma'
    | '/quadro'
    | '/tabelas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/eletrocalha'
    | '/eletroduto'
    | '/envelope'
    | '/memoria'
    | '/norma'
    | '/quadro'
    | '/tabelas'
  id:
    | '__root__'
    | '/'
    | '/eletrocalha'
    | '/eletroduto'
    | '/envelope'
    | '/memoria'
    | '/norma'
    | '/quadro'
    | '/tabelas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EletrocalhaRoute: typeof EletrocalhaRoute
  EletrodutoRoute: typeof EletrodutoRoute
  EnvelopeRoute: typeof EnvelopeRoute
  MemoriaRoute: typeof MemoriaRoute
  NormaRoute: typeof NormaRoute
  QuadroRoute: typeof QuadroRoute
  TabelasRoute: typeof TabelasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eletrocalha': {
      id: '/eletrocalha'
      path: '/eletrocalha'
      fullPath: '/eletrocalha'
      preLoaderRoute: typeof EletrocalhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eletroduto': {
      id: '/eletroduto'
      path: '/eletroduto'
      fullPath: '/eletroduto'
      preLoaderRoute: typeof EletrodutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/envelope': {
      id: '/envelope'
      path: '/envelope'
      fullPath: '/envelope'
      preLoaderRoute: typeof EnvelopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memoria': {
      id: '/memoria'
      path: '/memoria'
      fullPath: '/memoria'
      preLoaderRoute: typeof MemoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/norma': {
      id: '/norma'
      path: '/norma'
      fullPath: '/norma'
      preLoaderRoute: typeof NormaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quadro': {
      id: '/quadro'
      path: '/quadro'
      fullPath: '/quadro'
      preLoaderRoute: typeof QuadroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabelas': {
      id: '/tabelas'
      path: '/tabelas'
      fullPath: '/tabelas'
      preLoaderRoute: typeof TabelasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EletrocalhaRoute: EletrocalhaRoute,
  EletrodutoRoute: EletrodutoRoute,
  EnvelopeRoute: EnvelopeRoute,
  MemoriaRoute: MemoriaRoute,
  NormaRoute: NormaRoute,
  QuadroRoute: QuadroRoute,
  TabelasRoute: TabelasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
